// Authoritative Metro 2 Base Segment field map — corrected twice:
// 2026-07-23 (Phase 3 defect report, P1-1) fixed the 19/20 and 21/22 swaps
// the reference corpus carried; 2026-07-24 research against a production
// Metro 2 implementation's field layout fixed the rest of the low-numbered
// fields the same corpus had wrong (Account Number is Field 7 not 1,
// Portfolio Type 8 not 2, High Credit 12 not 9, Terms Duration 13 not 12,
// Date Opened 10 not 13, Date of Last Payment 27 not 23).
//
// Canonical base-segment order (CDIA CRRG): 7 Consumer Account Number,
// 8 Portfolio Type, 9 Account Type, 10 Date Opened, 11 Credit Limit,
// 12 Highest Credit/Original Loan Amount, 13 Terms Duration, 14 Terms
// Frequency, 15 Scheduled Monthly Payment, 16 Actual Payment, 17A Account
// Status, 17B Payment Rating, 18 Payment History Profile, 19 Special
// Comment, 20 Compliance Condition Code, 21 Current Balance, 22 Amount
// Past Due, 23 Original Charge-off Amount, 24 Date of Account Information,
// 25 FCRA Compliance Date (DOFD), 26 Date Closed, 27 Date of Last Payment.
// This is the single source of truth — masterPrompt.js's field table
// mirrors it; never inline a field number as a string again.
export const METRO2_FIELDS = {
  CONSUMER_ACCOUNT_NUMBER: { num: '7', name: 'Consumer Account Number' },
  PORTFOLIO_TYPE: { num: '8', name: 'Portfolio Type' },
  ACCOUNT_TYPE: { num: '9', name: 'Account Type' },
  DATE_OPENED: { num: '10', name: 'Date Opened' },
  CREDIT_LIMIT: { num: '11', name: 'Credit Limit' },
  HIGHEST_CREDIT: { num: '12', name: 'Highest Credit or Original Loan Amount' },
  TERMS_DURATION: { num: '13', name: 'Terms Duration' },
  TERMS_FREQUENCY: { num: '14', name: 'Terms Frequency' },
  SCHEDULED_MONTHLY_PAYMENT: { num: '15', name: 'Scheduled Monthly Payment Amount' },
  ACTUAL_PAYMENT: { num: '16', name: 'Actual Payment Amount' },
  ACCOUNT_STATUS: { num: '17A', name: 'Account Status' },
  PAYMENT_RATING: { num: '17B', name: 'Payment Rating' },
  PAYMENT_HISTORY_PROFILE: { num: '18', name: 'Payment History Profile' },
  SPECIAL_COMMENT: { num: '19', name: 'Special Comment' },
  COMPLIANCE_CONDITION_CODE: { num: '20', name: 'Compliance Condition Code' },
  CURRENT_BALANCE: { num: '21', name: 'Current Balance' },
  AMOUNT_PAST_DUE: { num: '22', name: 'Amount Past Due' },
  ORIGINAL_CHARGE_OFF_AMT: { num: '23', name: 'Original Charge-off Amount' },
  DATE_OF_ACCOUNT_INFO: { num: '24', name: 'Date of Account Information' },
  DATE_FIRST_DELINQUENCY: { num: '25', name: 'FCRA Compliance Date (Date of First Delinquency)' },
  DATE_CLOSED: { num: '26', name: 'Date Closed' },
  DATE_LAST_PAYMENT: { num: '27', name: 'Date of Last Payment' },
};

// Account Status (Field 17A) codes — the prior list in the reference corpus
// mislabeled the delinquency ladder (71 is NOT "Settled"; 71-84 are
// time-based past-due stages that routinely carry balances and are NOT
// violations by themselves).
export const METRO2_STATUS_CODES = {
  '05': 'Account transferred',
  '11': 'Current account (0–29 days past due)',
  '13': 'Paid or closed account / zero balance',
  '61': 'Account paid in full, was a voluntary surrender',
  '62': 'Account paid in full, was a collection account',
  '63': 'Account paid in full, was a repossession',
  '64': 'Account paid in full, was a charge-off',
  '65': 'Account paid in full, a foreclosure was started',
  '71': '30–59 days past the due date',
  '78': '60–89 days past the due date',
  '80': '90–119 days past the due date',
  '82': '120–149 days past the due date',
  '83': '150–179 days past the due date',
  '84': '180 or more days past the due date',
  '88': 'Claim filed with government for insured portion of balance',
  '89': 'Deed received in lieu of foreclosure',
  '93': 'Account assigned to internal or external collections',
  '94': 'Foreclosure completed',
  '95': 'Voluntary surrender',
  '96': 'Merchandise repossessed',
  '97': 'Unpaid balance reported as a loss (charge-off)',
  'DA': 'Delete entire account (non-fraud)',
  'DF': 'Delete entire account (confirmed fraud)',
};

// "Field 25 (FCRA Compliance Date (Date of First Delinquency))" style —
// matches how violations[].field is generated by the audit prompt.
export function formatMetro2Field(key) {
  const f = METRO2_FIELDS[key];
  if (!f) return null;
  return `Field ${f.num} (${f.name})`;
}
