// Authoritative Metro 2 Base Segment field map — verified against the CDIA
// Credit Reporting Resource Guide (2026-07-23 Phase 3 defect report, P1-1).
//
// The reference corpus this app's prompts were built from had Field 19 and
// Field 20 swapped (Field 19 mislabeled "Compliance Condition Code" — that's
// actually Field 20; Field 19 is Special Comment) and Field 21/22 swapped
// the same way (21 mislabeled "Amount Past Due" — that's actually Field 22;
// 21 is Current Balance). Every letter generated against that corpus
// inherited the error. This is the single source of truth going forward —
// masterPrompt.js's field-reference table was rewritten to match this
// exactly; any future prompt or UI text referencing a Metro 2 field number
// should import from here rather than inlining a number as a string again.
export const METRO2_FIELDS = {
  ACCOUNT_NUMBER: { num: '1', name: 'Account Number' },
  PORTFOLIO_TYPE: { num: '2', name: 'Portfolio Type' },
  HIGH_CREDIT: { num: '9', name: 'High Credit' },
  TERMS_DURATION: { num: '12', name: 'Terms Duration' },
  DATE_OPENED: { num: '13', name: 'Date Opened' },
  MONTHLY_PAYMENT: { num: '15', name: 'Monthly Payment' },
  ACCOUNT_STATUS: { num: '17A', name: 'Account Status' },
  PAYMENT_RATING: { num: '17B', name: 'Payment Rating' },
  PAYMENT_HISTORY_PROFILE: { num: '18', name: 'Payment History Profile' },
  SPECIAL_COMMENT: { num: '19', name: 'Special Comment' },
  COMPLIANCE_CONDITION_CODE: { num: '20', name: 'Compliance Condition Code' },
  CURRENT_BALANCE: { num: '21', name: 'Current Balance' },
  AMOUNT_PAST_DUE: { num: '22', name: 'Amount Past Due' },
  ORIGINAL_CHARGE_OFF_AMT: { num: '23', name: 'Original Charge-off Amount' },
  DATE_OF_ACCOUNT_INFO: { num: '24', name: 'Date of Account Information' },
  DATE_FIRST_DELINQUENCY: { num: '25', name: 'Date of First Delinquency' },
};

// "Field 25 (DOFD)" style — matches how violations[].field is generated by
// the audit prompt (see masterPrompt.js §10 schema description).
export function formatMetro2Field(key) {
  const f = METRO2_FIELDS[key];
  if (!f) return null;
  return `Field ${f.num} (${f.name})`;
}
